image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - staging

install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - "jest --ci"

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - master
