# We will try to use machine (Linux) that includes node.js (temporary)
image: node:13-alpine

stages:
  - test
  - production

test:
  type: test
  stage: test
  services:
    - postgres:14-alpine # Add postgres service in Gitlab to test the code
  script:
    - npm i
    # - npx sequelize db:create
    # - npx sequelize db:migrate
    # - npx sequelize db:seed:all
    - npm run test # It will run test in Gitlab before it upload to heroku
  only:
    - minggu-kelabu

production:
  type: deploy
  stage: production
  image: ruby:3 # Using ruby image to deploy to heroku
  script:
    # dpl is package to deploy to heroku
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - minggu-kelabu
