export const GET_MOVIES_BEGIN = "GET_MOVIES_BEGIN";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_MOVIE_DETAIL_BEGIN = "GET_MOVIE_DETAIL_BEGIN";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAIL = "GET_MOVIE_DETAIL_FAIL";

export const POST_MOVIE_BEGIN = "POST_MOVIE_BEGIN";
export const POST_MOVIE_SUCCESS = "POST_MOVIE_SUCCESS";
export const POST_MOVIE_FAIL = "POST_MOVIE_FAIL";
